# Generated by Django 4.2 on 2024-01-12 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_phone_number_customuser_vehicle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='vehicle_image',
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
